name: Build LaTeX and Deploy PDFs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Compile and create index using Docker
        run: |
          mkdir public
          docker run --rm -v "$(pwd):/data" texlive/texlive:latest /bin/bash -c " \
            find /data -name \"main.tex\" | while read -r tex_file; do \
              dir=$(dirname \"$tex_file\"); \
              # Go to the directory and compile
              cd \"$dir\"; \
              pdflatex -interaction=nonstopmode main.tex; \
              # Go back to the root
              cd /data; \
              # Check if the PDF file was successfully created
              if [ -f \"$dir/main.pdf\" ]; then \
                relative_path=${dir#./}; \
                sanitized_name=$(echo \"$relative_path\" | sed 's/\//_/g'); \
                cp \"$dir/main.pdf\" \"/data/public/$sanitized_name.pdf\"; \
              else \
                echo \"Compilation failed for $tex_file\"; \
              fi; \
            done \
          "

      - name: Create index.html
        run: |
          echo "<!DOCTYPE html><html><body><h1>PDF Documents</h1><ul>" > public/index.html
          # Use 'ls' to check for files before looping
          if ls public/*.pdf 1> /dev/null 2>&1; then
            for pdf in public/*.pdf; do
              link_text=$(basename "$pdf" | sed 's/\.pdf//' | sed 's/_/ /g')
              echo "<li><a href=\"$(basename "$pdf")\">$link_text</a></li>" >> public/index.html
            done
          else
            echo "<li>No PDF files were compiled.</li>" >> public/index.html
          fi
          echo "</ul></body></html>" >> public/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
